ArcticDB 3.0.0 release
conda-forge/arcticdb-feedstock pull request #53
Opened 2023-09-01 15:11 UTC by poodlewars

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-09-01 15:43 UTC, jjerphan reviewed
@conda-forge-admin, please rerender

2023-09-01 15:43 UTC, jjerphan commented on recipe/meta.yaml
> +  sha256: 22745af39d7be461dc5ba13e6afd25e1bad5709673d78a1f609708f70c3cd711
```suggestion
  sha256: 6d2d68e8b931d8a871f9034eaabe48acdfe3578d7c5862122dce119b7d867947
```

2023-09-01 15:43 UTC, jjerphan commented on recipe/meta.yaml
>    patches:
Side-note: the `patches` section can be removed since https://github.com/man-group/ArcticDB/issues/662 has been merged.

2023-09-01 16:35 UTC, jjerphan approved these changes
LGTM given 🟢 CI checks.

Thank you, @poodlewars.

I will rename the title of this PR for consistency with the previous PRs'.

2023-09-04 07:18 UTC, jjerphan requested changes
Since https://github.com/man-group/ArcticDB/pull/761 which introduce the dependence of `pymongo` is part of this release, `pymongo` must also be added to the `run` requirements.

2023-09-04 14:55 UTC, phoebusm commented
@jjerphan `pymongo` dependency is for testing only. It should not be required in the `run` requirements.

2023-09-04 15:00 UTC, jjerphan submitted a review, later dismissed
OK then LGTM.

We just need to document this line [update this line](https://github.com/man-group/ArcticDB/blob/a491bb03416e5dd419691abe0da096bb1127e89e/environment_unix.yml#L68).

2023-09-13 14:13 UTC, jjerphan commented on recipe/meta.yaml
Some libraries of of the Azure SDK from C++ need to be added to `host`, see https://github.com/conda-forge/arcticdb-feedstock/pull/56/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR69-R71.

2023-09-13 14:26 UTC, jjerphan commented on recipe/meta.yaml
> +    - azure-identity-cpp
We also need to explicitly add `azure-core-cpp` for now.
```suggestion
    - azure-core-cpp
    - azure-identity-cpp
```

2023-09-13 14:59 UTC, jjerphan approved these changes
LGTM given :green_circle: CI checks.

2023-09-13 17:25 UTC, merged