Unpin `libevent` and `msgpack_c`
conda-forge/arcticdb-feedstock pull request #63
Opened 2023-09-21 15:51 UTC by jjerphan

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2023-09-21 15:51 UTC, jjerphan commented
@conda-forge-admin, please rerender

2023-09-21 16:13 UTC, jjerphan commented
@conda-forge-admin, please rerender

2023-09-22 07:37 UTC, JohanMabille requested changes

2023-09-22 07:37 UTC, JohanMabille commented on recipe/meta.yaml
> +    - lmdb
See my comment[here](https://github.com/conda-forge/arcticdb-feedstock/pull/61#discussion_r1333987709)

2023-09-26 15:22 UTC, JohanMabille approved these changes

2023-09-26 16:53 UTC, merged